export const ALL_SCOPES = [
  "catalog:read",
  "catalog:write",
  "customers:read",
  "customers:pii:read",
  "customers:write",
  "customers:merge",
  "orders:read",
  "orders:write",
  "orders:lifecycle",
  "orders:cancel",
  "payments:read",
  "payments:write",
  "payments:reverse",
  "payments:refund",
  "transactions:read",
  "transactions:write",
  "transactions:reverse",
  "reports:read",
  "settings:read",
  "settings:write",
  "backups:export",
  "backups:import",
  "backups:restore",
  "audit:read",
  "migration:reconcile",
] as const;

export type Scope = (typeof ALL_SCOPES)[number];

export type OperationKind = "query" | "command" | "preview" | "confirm";

export interface OperationPolicy {
  operationId: string;
  tool: string | null;
  kind: OperationKind;
  scopes: Scope[];
  public?: boolean;
  sensitiveRead?: boolean;
  retryable?: boolean;
}

export const LEGACY_OPERATION_ALLOWLIST = new Set<string>([
  "getStatus",
  "getCapabilities",
  "listPublicProducts",
  "getPublicProduct",
  "listPublicCategories",
  "getPublicSettings",
  "listProducts",
  "getProduct",
  "createProduct",
  "updateProduct",
  "archiveProduct",
  "restoreProduct",
  "listCategories",
  "createCategory",
  "updateCategory",
  "archiveCategory",
  "restoreCategory",
  "listCustomers",
  "createCustomer",
  "updateCustomer",
  "archiveCustomer",
  "listOrders",
  "getOrder",
  "getOrderInvoice",
  "createDraftOrder",
  "updateDraftOrder",
  "discardDraftOrder",
  "restoreDraftOrder",
  "confirmOrder",
  "markOrderShipping",
  "completeOrder",
  "cloneOrder",
  "previewOrderCancellation",
  "confirmOrderCancellation",
  "recordPayment",
  "listPayments",
  "listReceivables",
  "previewPaymentRefund",
  "confirmPaymentRefund",
  "listCashTransactions",
  "createCashTransaction",
  "previewCashReversal",
  "confirmCashReversal",
  "getReportSummary",
  "getPhoneSettings",
  "updatePhoneSettings",
  "getShopSettings",
  "updateShopSettings",
  "getBankSettings",
  "updateBankSettings",
  "getTaxSettings",
  "updateTaxSettings",
  "listShopTemplates",
  "createShopTemplate",
  "updateShopTemplate",
  "archiveShopTemplate",
  "restoreShopTemplate",
  "setDefaultShopTemplate",
]);

export const OPERATIONS: OperationPolicy[] = [
  { operationId: "getStatus", tool: "giaban_get_status", kind: "query", scopes: [] },
  { operationId: "getCapabilities", tool: "giaban_get_capabilities", kind: "query", scopes: [] },
  { operationId: "listPublicProducts", tool: null, kind: "query", scopes: [], public: true },
  { operationId: "getPublicProduct", tool: null, kind: "query", scopes: [], public: true },
  { operationId: "listPublicCategories", tool: null, kind: "query", scopes: [], public: true },
  { operationId: "getPublicSettings", tool: null, kind: "query", scopes: [], public: true },
  { operationId: "listProducts", tool: "giaban_list_products", kind: "query", scopes: ["catalog:read"] },
  { operationId: "getProduct", tool: "giaban_get_product", kind: "query", scopes: ["catalog:read"] },
  { operationId: "createProduct", tool: "giaban_create_product", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "updateProduct", tool: "giaban_update_product", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "archiveProduct", tool: "giaban_archive_product", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "restoreProduct", tool: "giaban_restore_product", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "listCategories", tool: "giaban_list_categories", kind: "query", scopes: ["catalog:read"] },
  { operationId: "createCategory", tool: "giaban_create_category", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "updateCategory", tool: "giaban_update_category", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "archiveCategory", tool: "giaban_archive_category", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "restoreCategory", tool: "giaban_restore_category", kind: "command", scopes: ["catalog:write"], retryable: true },
  { operationId: "listCustomers", tool: "giaban_list_customers", kind: "query", scopes: ["customers:read"] },
  { operationId: "getCustomer", tool: "giaban_get_customer", kind: "query", scopes: ["customers:read", "customers:pii:read"], sensitiveRead: true },
  { operationId: "createCustomer", tool: "giaban_create_customer", kind: "command", scopes: ["customers:write"], retryable: true },
  { operationId: "updateCustomer", tool: "giaban_update_customer", kind: "command", scopes: ["customers:write"], retryable: true },
  { operationId: "archiveCustomer", tool: "giaban_archive_customer", kind: "command", scopes: ["customers:write"], retryable: true },
  { operationId: "restoreCustomer", tool: "giaban_restore_customer", kind: "command", scopes: ["customers:write"], retryable: true },
  { operationId: "previewCustomerMerge", tool: "giaban_preview_customer_merge", kind: "preview", scopes: ["customers:merge"] },
  { operationId: "confirmCustomerMerge", tool: "giaban_confirm_customer_merge", kind: "confirm", scopes: ["customers:merge"] },
  { operationId: "previewCustomerUnmerge", tool: "giaban_preview_customer_unmerge", kind: "preview", scopes: ["customers:merge"] },
  { operationId: "confirmCustomerUnmerge", tool: "giaban_confirm_customer_unmerge", kind: "confirm", scopes: ["customers:merge"] },
  { operationId: "listOrders", tool: "giaban_list_orders", kind: "query", scopes: ["orders:read"] },
  { operationId: "getOrder", tool: "giaban_get_order", kind: "query", scopes: ["orders:read"] },
  { operationId: "getOrderInvoice", tool: "giaban_get_order_invoice", kind: "query", scopes: ["orders:read", "customers:pii:read"], sensitiveRead: true },
  { operationId: "createDraftOrder", tool: "giaban_create_draft_order", kind: "command", scopes: ["orders:write"], retryable: true },
  { operationId: "updateDraftOrder", tool: "giaban_update_draft_order", kind: "command", scopes: ["orders:write"], retryable: true },
  { operationId: "discardDraftOrder", tool: "giaban_discard_draft_order", kind: "command", scopes: ["orders:write"], retryable: true },
  { operationId: "restoreDraftOrder", tool: "giaban_restore_draft_order", kind: "command", scopes: ["orders:write"], retryable: true },
  { operationId: "confirmOrder", tool: "giaban_confirm_order", kind: "command", scopes: ["orders:lifecycle"], retryable: true },
  { operationId: "markOrderShipping", tool: "giaban_mark_order_shipping", kind: "command", scopes: ["orders:lifecycle"], retryable: true },
  { operationId: "completeOrder", tool: "giaban_complete_order", kind: "command", scopes: ["orders:lifecycle"], retryable: true },
  { operationId: "cloneOrder", tool: "giaban_clone_order", kind: "command", scopes: ["orders:write"], retryable: true },
  { operationId: "previewOrderCancellation", tool: "giaban_preview_order_cancellation", kind: "preview", scopes: ["orders:cancel"] },
  { operationId: "confirmOrderCancellation", tool: "giaban_confirm_order_cancellation", kind: "confirm", scopes: ["orders:cancel"] },
  { operationId: "recordPayment", tool: "giaban_record_payment", kind: "command", scopes: ["payments:write"], retryable: true },
  { operationId: "listPayments", tool: "giaban_list_payments", kind: "query", scopes: ["payments:read"] },
  { operationId: "listReceivables", tool: "giaban_list_receivables", kind: "query", scopes: ["payments:read"] },
  { operationId: "previewPaymentReversal", tool: "giaban_preview_payment_reversal", kind: "preview", scopes: ["payments:reverse"] },
  { operationId: "confirmPaymentReversal", tool: "giaban_confirm_payment_reversal", kind: "confirm", scopes: ["payments:reverse"] },
  { operationId: "previewPaymentRefund", tool: "giaban_preview_payment_refund", kind: "preview", scopes: ["payments:refund"] },
  { operationId: "confirmPaymentRefund", tool: "giaban_confirm_payment_refund", kind: "confirm", scopes: ["payments:refund"] },
  { operationId: "listCashTransactions", tool: "giaban_list_cash_transactions", kind: "query", scopes: ["transactions:read"] },
  { operationId: "createCashTransaction", tool: "giaban_create_cash_transaction", kind: "command", scopes: ["transactions:write"], retryable: true },
  { operationId: "previewCashReversal", tool: "giaban_preview_cash_reversal", kind: "preview", scopes: ["transactions:reverse"] },
  { operationId: "confirmCashReversal", tool: "giaban_confirm_cash_reversal", kind: "confirm", scopes: ["transactions:reverse"] },
  { operationId: "getReportSummary", tool: "giaban_get_report_summary", kind: "query", scopes: ["reports:read"] },
  { operationId: "getConfirmedSalesReport", tool: "giaban_get_confirmed_sales_report", kind: "query", scopes: ["reports:read"] },
  { operationId: "getReceiptsReport", tool: "giaban_get_receipts_report", kind: "query", scopes: ["reports:read"] },
  { operationId: "getReceivablesReport", tool: "giaban_get_receivables_report", kind: "query", scopes: ["reports:read"] },
  { operationId: "getDiscountsShippingReport", tool: "giaban_get_discounts_shipping_report", kind: "query", scopes: ["reports:read"] },
  { operationId: "getCogsProfitReport", tool: "giaban_get_cogs_profit_report", kind: "query", scopes: ["reports:read"] },
  { operationId: "getPhoneSettings", tool: "giaban_get_phone_settings", kind: "query", scopes: ["settings:read"] },
  { operationId: "updatePhoneSettings", tool: "giaban_update_phone_settings", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "getShopSettings", tool: "giaban_get_shop_settings", kind: "query", scopes: ["settings:read"] },
  { operationId: "updateShopSettings", tool: "giaban_update_shop_settings", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "getBankSettings", tool: "giaban_get_bank_settings", kind: "query", scopes: ["settings:read"] },
  { operationId: "updateBankSettings", tool: "giaban_update_bank_settings", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "getTaxSettings", tool: "giaban_get_tax_settings", kind: "query", scopes: ["settings:read"] },
  { operationId: "updateTaxSettings", tool: "giaban_update_tax_settings", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "listShopTemplates", tool: "giaban_list_shop_templates", kind: "query", scopes: ["settings:read"] },
  { operationId: "createShopTemplate", tool: "giaban_create_shop_template", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "updateShopTemplate", tool: "giaban_update_shop_template", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "archiveShopTemplate", tool: "giaban_archive_shop_template", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "restoreShopTemplate", tool: "giaban_restore_shop_template", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "setDefaultShopTemplate", tool: "giaban_set_default_shop_template", kind: "command", scopes: ["settings:write"], retryable: true },
  { operationId: "previewBackupExport", tool: "giaban_preview_backup_export", kind: "preview", scopes: ["backups:export"] },
  { operationId: "confirmBackupExport", tool: "giaban_confirm_backup_export", kind: "confirm", scopes: ["backups:export"] },
  { operationId: "getBackupManifest", tool: "giaban_get_backup_manifest", kind: "query", scopes: ["backups:export"] },
  { operationId: "createBackupDownloadGrant", tool: "giaban_create_backup_download_grant", kind: "command", scopes: ["backups:export"], retryable: true },
  { operationId: "createBackupUploadIntent", tool: "giaban_create_backup_upload_intent", kind: "command", scopes: ["backups:import"], retryable: true },
  { operationId: "finalizeBackupUpload", tool: "giaban_finalize_backup_upload", kind: "command", scopes: ["backups:import"], retryable: true },
  { operationId: "previewRestore", tool: "giaban_preview_restore", kind: "preview", scopes: ["backups:restore"] },
  { operationId: "confirmRestore", tool: "giaban_confirm_restore", kind: "confirm", scopes: ["backups:restore"] },
  { operationId: "searchAuditEvents", tool: "giaban_search_audit_events", kind: "query", scopes: ["audit:read"] },
  { operationId: "previewLiveReconciliation", tool: "giaban_preview_live_reconciliation", kind: "preview", scopes: ["migration:reconcile"] },
  { operationId: "confirmLiveReconciliation", tool: "giaban_confirm_live_reconciliation", kind: "confirm", scopes: ["migration:reconcile"] },
];

export const operationById = new Map(OPERATIONS.map((operation) => [operation.operationId, operation]));
export const operationByTool = new Map(
  OPERATIONS.filter((operation) => operation.tool).map((operation) => [operation.tool as string, operation]),
);
